### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by pooyapro**

### CODE REVIEW

**Comment by blackavec** [comment]
@pooyapro man in PR ro mibandam. 
oon foldere d-web-static-master ro delete kon lotfan va taghirateto too hamin root e asli emal kon 
niaz be add kardane directory jadid ya file jadid nadare faghat index ro copy kon az roo assets haye oon ye page jadid besaz ;)

**Comment by blackavec** [comment]
@pooyapro rasti lotfan ye title monaseb ham be pull request va branchi ke misazi bede. 
ina bara inke bedoonim ki roo chi kar karde kheili moheme

**Comment by pooyapro** [comment]
@mahanhaz  chashm ;)

**Comment by blackavec** [comment]
@pooyapro ok dame shoma garm. hal shod PR ro khodet open kon
man badesh review mikonam

**Pull request closed without merging**
